In [12]:
from ingestion import CSVReader

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
csv_reader = CSVReader()

In [22]:
df = csv_reader.lazy_extract("./Data/BeerAdvocate/beers.csv")
df = df.drop(columns="beer_name")
df.head(100000)

,beer_id,brewery_id,brewery_name,style,nbr_ratings,nbr_reviews,avg,ba_score,bros_score,abv,avg_computed,zscore,nbr_matched_valid_ratings,avg_matched_valid_ratings
0,166064,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,4.7,NaN,NaN,0,NaN
1,166065,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,3.8,NaN,NaN,0,NaN
2,166066,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,4.8,NaN,NaN,0,NaN
3,166067,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,4.0,NaN,NaN,0,NaN
4,166063,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,4.5,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,47365,9823,Downtown Joe's American Bar And Grill,Extra Special / Strong Bitter (ESB),1,1,4.76,NaN,NaN,NaN,4.760000,NaN,0,NaN
99996,47362,9823,Downtown Joe's American Bar And Grill,American Double / Imperial IPA,12,3,4.04,85.0,NaN,NaN,4.101667,NaN,0,NaN
99997,113689,9823,Downtown Joe's American Bar And Grill,Schwarzbier,1,0,3.50,NaN,NaN,NaN,3.500000,NaN,0,NaN
99998,35614,9823,Downtown Joe's American Bar And Grill,Extra Special / Strong Bitter (ESB),5,2,3.73,NaN,NaN,NaN,3.656000,NaN,0,NaN
99999,201822,9823,Downtown Joe's American Bar And Grill,American Pale Ale (APA),1,0,3.71,NaN,NaN,NaN,3.710000,NaN,0,NaN

In [23]:
df = csv_reader.extract("./Data/BeerAdvocate/beers.csv")
df = df.drop(columns="beer_name")
df.head(100000)

,beer_id,brewery_id,brewery_name,style,nbr_ratings,nbr_reviews,avg,ba_score,bros_score,abv,avg_computed,zscore,nbr_matched_valid_ratings,avg_matched_valid_ratings
0,166064,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,4.7,NaN,NaN,0,NaN
1,166065,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,3.8,NaN,NaN,0,NaN
2,166066,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,4.8,NaN,NaN,0,NaN
3,166067,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,4.0,NaN,NaN,0,NaN
4,166063,39912,Abdysh-Ata (Абдыш Ата),Euro Pale Lager,0,0,NaN,NaN,NaN,4.5,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,47365,9823,Downtown Joe's American Bar And Grill,Extra Special / Strong Bitter (ESB),1,1,4.76,NaN,NaN,NaN,4.760000,NaN,0,NaN
99996,47362,9823,Downtown Joe's American Bar And Grill,American Double / Imperial IPA,12,3,4.04,85.0,NaN,NaN,4.101667,NaN,0,NaN
99997,113689,9823,Downtown Joe's American Bar And Grill,Schwarzbier,1,0,3.50,NaN,NaN,NaN,3.500000,NaN,0,NaN
99998,35614,9823,Downtown Joe's American Bar And Grill,Extra Special / Strong Bitter (ESB),5,2,3.73,NaN,NaN,NaN,3.656000,NaN,0,NaN
99999,201822,9823,Downtown Joe's American Bar And Grill,American Pale Ale (APA),1,0,3.71,NaN,NaN,NaN,3.710000,NaN,0,NaN